name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: apps/backend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd apps/backend
        npm ci
    
    - name: Run tests
      run: |
        cd apps/backend
        npm run test
    
    - name: Run linting
      run: |
        cd apps/backend
        npm run lint
    
    - name: Run type checking
      run: |
        cd apps/backend
        npm run type-check

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: apps/frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd apps/frontend
        npm ci
    
    - name: Run tests
      run: |
        cd apps/frontend
        npm run test
    
    - name: Run linting
      run: |
        cd apps/frontend
        npm run lint
    
    - name: Run type checking
      run: |
        cd apps/frontend
        npm run type-check 